#ifndef __cmdline__
#define __cmdline__
/*****
  command line parser interface 
                        -- generated by clig (Version: 1996-09-15)

  The command line parser `clig':
  (C) 1995 Harald Kirsch (kir@iitb.fhg.de)
*****/

/***** 
  for better support of LCLint, we need this:
*/
#ifndef __bool__
#define __bool__
typedef unsigned char bool;
#ifndef FALSE
#  define FALSE (1==0)
#  define TRUE  (!FALSE)
#endif
#endif

typedef struct s_Cmdline {
  /***** -b: buffer size in kB */
  bool bsizeP;
  int bsize;
  int bsizeC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

