#ifndef __cmdline__
#define __cmdline__
/*****
  command line parser interface 
                        -- generated by clig (Version: 1997-09-05)

  The command line parser `clig':
  (C) 1995 Harald Kirsch (kir@iitb.fhg.de)
*****/

#ifndef FALSE
#  define FALSE (1==0)
#  define TRUE  (!FALSE)
#endif

typedef struct s_Cmdline {
  /***** -b: buffer size in kB */
  char bsizeP;
  int bsize;
  int bsizeC;
  /***** -vt: show throughput */
  char vtP;
  /***** -vr: show read-times */
  char vrP;
  /***** -vw: show write-times */
  char vwP;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

